files:[
  {
    "source" : "/Xliff/nb.xcloc/Localized Contents/nb.xliff"
    "translation" : "/Xliff/%two_letters_code%_%original_file_name%"
  },
  {
    "source" : "/Xliff/de.xcloc/Localized Contents/de.xliff"
    "translation" : "/Xliff/%two_letters_code%_%original_file_name%"
  },
  {
    "source" : "/Xliff/zh-Hans.xcloc/Localized Contents/zh-Hans.xliff"
    "translation" : "/Xliff/%two_letters_code%_%original_file_name%"
  }
]
